import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {AreaChart, Area, ResponsiveContainer, Tooltip, XAxis, BarChart, Bar, PieChart, Pie, Cell} from 'recharts';
import {LayoutDashboard, Bot, ChartNoAxesCombined, Lightbulb, BookOpen, ShieldCheck, Target, Info, Leaf, AlertTriangle, Send, Database} from 'lucide-react';
import './styles.css';

const API=(import.meta.env.VITE_API_URL || 'https://greenpulse-ai-sustainability.onrender.com').replace(/\/$/, '');
type Finding={id:string;resource_type:string;location:string;observed_value:number;baseline_value:number;unit:string;difference_percent:number;priority:string;reason:string;finding:string};
const nav=[
  {name:'Dashboard',path:'/',Icon:LayoutDashboard},
  {name:'AI Assistant',path:'/assistant',Icon:Bot},
  {name:'Resource Analysis',path:'/analysis',Icon:ChartNoAxesCombined},
  {name:'Recommendations',path:'/recommendations',Icon:Lightbulb},
  {name:'Knowledge Base',path:'/knowledge',Icon:BookOpen},
  {name:'Responsible AI',path:'/responsible-ai',Icon:ShieldCheck},
  {name:'SDG Alignment',path:'/sdg',Icon:Target},
  {name:'About Project',path:'/about',Icon:Info},
] as const;
type RoutePath = typeof nav[number]['path'];
const routeForPath = (pathname: string): RoutePath =>
  (nav.find(item => item.path === pathname)?.path ?? '/');
const colors=['#27a078','#4db98e','#d3b347','#e76f51'];
function api(path:string, options?:RequestInit){return fetch(API+path,options).then(r=>{if(!r.ok) throw new Error('Backend request failed');return r.json()})}
function Badge({children}:{children:React.ReactNode}){return <span className="badge">{children}</span>}
function Dashboard({summary,trends,findings}:{summary:any,trends:any[],findings:Finding[]}){const dist=Object.entries(summary?.by_resource||{}).map(([name,value])=>({name,value}));return <><section className="hero"><div><Badge>DEMO DATASET · SIMULATED RESOURCE DATA</Badge><h1>Sustainable Campus Overview</h1><p>Understand simulated resource patterns, investigate unusual use, and turn grounded insight into practical next steps.</p></div><div className="mode"><Bot/> <b>Demo AI Mode</b><small>Local RAG fallback active</small></div></section><div className="metrics">{[['Resource records',summary?.total_records||'—'],['Electricity records',summary?.by_resource?.Electricity||'—'],['High-use alerts',summary?.high_consumption_alerts||'—'],['Actions suggested',summary?.sustainability_actions||'—']].map(x=><article className="metric" key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><small>Simulated data</small></article>)}</div><div className="grid two"><section className="card"><h2>28-day resource trend</h2><p className="muted">Daily combined values by resource category</p><div className="chart"><ResponsiveContainer><AreaChart data={trends}><XAxis dataKey="date" hide/><Tooltip/><Area dataKey="Electricity" stroke="#27a078" fill="#bde9d7"/><Area dataKey="Water" stroke="#3f8fcf" fill="#c9e3f5"/></AreaChart></ResponsiveContainer></div></section><section className="card"><h2>Dataset distribution</h2><div className="chart"><ResponsiveContainer><PieChart><Pie data={dist} dataKey="value" nameKey="name" outerRadius={90}>{dist.map((_:any,i:number)=><Cell key={i} fill={colors[i]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="legend">{dist.map((x:any,i)=><span key={x.name}><i style={{background:colors[i]}}/> {x.name}</span>)}</div></section></div><section className="card"><div className="title-row"><div><h2>Priority attention</h2><p className="muted">Transparent flags based on recent versus historical demo averages.</p></div><Badge>{findings.length} alerts</Badge></div>{findings.slice(0,3).map(f=><div className="alert" key={f.id}><AlertTriangle/><div><b>{f.finding}</b><p>{f.reason}</p></div><strong>{f.priority}</strong></div>)}</section></>}
function Analysis({findings, load}:{findings:Finding[],load:(type?:string)=>void}){const [type,setType]=useState('Electricity'); return <><section className="pagehead"><Badge>EXPLAINABLE ANALYSIS</Badge><h1>Resource Consumption Analysis</h1><p>Compare current simulated usage against an earlier reference period.</p></section><section className="card controls"><label>Resource category<select value={type} onChange={e=>setType(e.target.value)}><option>Electricity</option><option>Water</option><option>Paper</option><option>Waste</option></select></label><button onClick={()=>load(type)}>Analyze resource</button></section>{findings.length?<div className="findings">{findings.map(f=><article className="card finding" key={f.id}><div className="title-row"><Badge>{f.priority} priority</Badge><span>{f.resource_type} · {f.location}</span></div><h2>{f.finding}</h2><div className="compare"><div><span>Observed (recent)</span><b>{f.observed_value} {f.unit}</b></div><div><span>Baseline (earlier)</span><b>{f.baseline_value} {f.unit}</b></div><div><span>Difference</span><b className="warning">+{f.difference_percent}%</b></div></div><p><b>Why flagged: </b>{f.reason}</p></article>)}</div>:<section className="empty">Choose a category and run transparent analysis.</section>}</>}
function Assistant(){const [message,setMessage]=useState('Why might electricity consumption suddenly increase in a campus building?');const [answer,setAnswer]=useState<any>();const [busy,setBusy]=useState(false);async function ask(e:React.FormEvent){e.preventDefault();setBusy(true);try{setAnswer(await api('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message})}))}catch{setAnswer({error:'The backend is unavailable. Start FastAPI to use the demo assistant.'})}finally{setBusy(false)}}const uniqueSources=answer?.sources?[...new Set(answer.sources as string[])]:[];return <><section className="pagehead"><Badge>RAG-GROUNDED · DEMO AI MODE</Badge><h1>Ask the Sustainability Assistant</h1><p>Responses use relevant local knowledge when available and name the source documents.</p></section><section className="chat card"><form onSubmit={ask}><label>Your question<input value={message} onChange={e=>setMessage(e.target.value)} aria-label="Your sustainability question"/></label><button disabled={busy}><Send size={17}/>{busy?'Thinking…':'Ask assistant'}</button></form>{answer&&<article className="answer"><b>Grounded response</b><p>{answer.answer||answer.error}</p>{uniqueSources.length>0&&<><small>Knowledge sources</small><div>{uniqueSources.map((s:string)=><Badge key={s}>{s}</Badge>)}</div></>}<p className="note">{answer.responsible_ai_note}</p></article>}</section></>}
function Recommendations(){const [items,setItems]=useState<any[]>([]);const [busy,setBusy]=useState(false);async function run(){setBusy(true);try{setItems((await api('/api/recommendations',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).items)}finally{setBusy(false)}}return <><section className="pagehead"><Badge>AGENTIC WORKFLOW</Badge><h1>Actionable Sustainability Recommendations</h1><p>Analysis, retrieval, recommendation and responsible AI checking are distinct, reviewable steps.</p></section><section className="workflow">{['1. Analyze demo data','2. Retrieve knowledge','3. Recommend action','4. Human review'].map(x=><span key={x}>{x}</span>)}</section><button onClick={run} disabled={busy}>{busy?'Generating…':'Generate recommendations'}</button><div className="findings">{items.map((x,i)=><article className="card finding" key={i}><div className="title-row"><Badge>{x.priority} priority</Badge><span>{x.status}</span></div><h2>{x.resource_category}: {x.recommendation}</h2><p><b>Finding: </b>{x.finding}</p><p><b>Reason: </b>{x.reason}</p><p><b>Supporting knowledge: </b>{x.supporting_knowledge}</p><p className="note">{x.responsible_ai_note}</p></article>)}</div></>}
function Knowledge(){const [data,setData]=useState<any>({items:[]});useEffect(()=>{api('/api/knowledge').then(setData).catch(()=>{})},[]);return <><section className="pagehead"><Badge>LOCAL RETRIEVAL INDEX</Badge><h1>Knowledge Base</h1><p>{data.document_count||0} source documents · {data.chunk_count||0} searchable knowledge chunks used to ground assistant responses.</p></section><div className="findings">{data.items.map((x:any)=><article className="card knowledge" key={x.source}><Database/><div><Badge>{x.category}</Badge><h2>{x.source}</h2><p>{x.description}</p><small>{x.chunk_count} searchable {x.chunk_count===1?'chunk':'chunks'}</small></div></article>)}</div></>}
const responsible=['Transparency — Demo AI Mode and simulated data are visibly labelled.','Explainability — Alerts show observed usage, baseline and reason.','Privacy — The prototype does not collect personal data.','Grounding — Assistant answers cite local knowledge files when found.','Human oversight — Recommendations are pending review, not autonomous decisions.','Limitations — Demo data is simulated and does not represent actual institutional consumption.'];
function InfoPage({page}:{page:string}){if(page==='Responsible AI')return <><section className="pagehead"><Badge>SAFETY & TRANSPARENCY</Badge><h1>Responsible AI & Data Transparency</h1><p>AI-generated recommendations are intended for decision support and should be reviewed by an appropriate human before implementation.</p></section><div className="findings">{responsible.map(x=><article className="card principle" key={x}><ShieldCheck/>{x}</article>)}</div></>;if(page==='SDG Alignment')return <><section className="pagehead"><Badge>NO OFFICIAL UN ENDORSEMENT</Badge><h1>SDG Alignment & Impact</h1><p>This student prototype aligns to SDG themes through awareness and decision support.</p></section><div className="sdgs"><article className="sdg primary"><b>12</b><h2>Responsible Consumption and Production</h2><p>Primary focus: resource awareness, waste reduction and more responsible campus practices.</p></article>{[['7','Affordable and Clean Energy','Encourages energy-efficiency conversations.'],['11','Sustainable Cities and Communities','Supports sustainable institutional environments.'],['13','Climate Action','Promotes climate-conscious behaviour.']].map(x=><article className="sdg" key={x[0]}><b>{x[0]}</b><h2>{x[1]}</h2><p>{x[2]}</p></article>)}</div></>;return <><section className="pagehead"><Badge>1M1B AI FOR SUSTAINABILITY</Badge><h1>About This Project</h1><p>A student prototype for a more informed, sustainable campus.</p></section><section className="card prose"><h2>From data to responsible action</h2><p>The AI-Powered Sustainable Campus Resource Assistant combines simulated resource analysis, local RAG retrieval and a transparent recommendation workflow. It is designed to demonstrate decision support—not to claim deployment or real-world impact.</p><h2>Target users</h2><p>Students, sustainability clubs, facilities teams and campus decision-makers who want a clear starting point for reviewing resource patterns.</p></section></>}
function App(){const [route,setRoute]=useState<RoutePath>(()=>routeForPath(window.location.pathname));const [summary,setSummary]=useState<any>();const [trends,setTrends]=useState<any[]>([]);const [findings,setFindings]=useState<Finding[]>([]);const [error,setError]=useState('');const navigate=(path:RoutePath)=>{window.history.pushState({},'',path);setRoute(path)};const load=async(type?:string)=>{try{setFindings((await api('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resource_type:type})})).findings)}catch{setError('Backend unavailable. Start the FastAPI server to load demo data.')}};useEffect(()=>{const onPopState=()=>setRoute(routeForPath(window.location.pathname));window.addEventListener('popstate',onPopState);return()=>window.removeEventListener('popstate',onPopState)},[]);useEffect(()=>{Promise.all([api('/api/resources/summary'),api('/api/resources/trends')]).then(([s,t])=>{setSummary(s);setTrends(t.items);load()}).catch(()=>setError('Backend unavailable. Start the FastAPI server to load demo data.'))},[]);let content=route==='/'?<Dashboard summary={summary} trends={trends} findings={findings}/>:route==='/analysis'?<Analysis findings={findings} load={load}/>:route==='/assistant'?<Assistant/>:route==='/recommendations'?<Recommendations/>:route==='/knowledge'?<Knowledge/>:<InfoPage page={nav.find(item=>item.path===route)?.name||'About Project'}/>;return <div className="app"><aside><div className="brand"><Leaf/> <span>Green<span>Pulse</span></span></div><p className="tagline">Sustainable campus intelligence</p><nav>{nav.map(({name,path,Icon})=>{const active=route===path;return <button className={active?'active':''} aria-current={active?'page':undefined} key={path} onClick={()=>navigate(path)}><Icon size={18}/>{name}</button>})}</nav><div className="side-note"><Badge>DEMO MODE</Badge><p>All resource information is simulated.</p></div></aside><main>{error&&<div className="error">{error}</div>}{content}<footer>Demo Dataset – Simulated Resource Data · Recommendations require human review.</footer></main></div>};createRoot(document.getElementById('root')!).render(<App/>);


